### ISSUE TITLE
The filename or extension is too long at OpenCppCoverage.VSPackage.CoverageRunner

### ISSUE THREAD

**Issue by dan31** [OpenCppCoverage/OpenCppCoverage#103]
**Describe the bug**

It is not a bug, but rather a limitation worth overcoming.

We have a fairly large solution with ~200 projects. When running `OpenCppCoverage` for one of them, the generated command is `44'000` symbols in length, possibly exceeding the `32'767`-ish limit hidden somewhere (`CreateProcessW`?):

```
...
--sources "c:\source"
--sources "c:\source\output_project_files_2019"
--sources "c:\source\output_project_files_2019\src\aclhelp"
--sources "c:\source\src\toolset"
...
```

Nothing fancy, simply lots of projects.

The error is:

```
...
System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at OpenCppCoverage.VSPackage.CoverageRunner.<>c__DisplayClass12_0.<<OnCoverageFinishedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

The OS fix `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` is already applied and set to 1.

**Expected behavior**

OpenCppCoverage works and runs as expected.

**Desktop (please complete the following information):**
- Version of OpenCppCoverage: 0.9.8.0. Visual Studio 2019 16.3.10 Pro.
- Architecture (x86/ x64): x64
- Windows version: Win10 x64 1903.

**Comment by OpenCppCoverage** [comment]
Hello,

Thank you for reporting this issue. 
I need to use [--config_file](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--config_file-arg) instead of passing all the command line options to OpenCppCoverage in [OpenCppCoverageCmdLine.cs](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/blob/master/VSPackage/OpenCppCoverageCmdLine.cs).  

In the meantime, does using a network drive reduce enough the length of the arguments to make the plugin works? Please see [Network path special considerations](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#network-path-special-considerations).
Unloading some projects can also help.

I hope it helps,

OpenCppCoverage

**Comment by dan31** [comment]
Thanks for a quick reply @OpenCppCoverage! 
I appreciate your suggestion with the network drive and I have actually tried, and it was just on the margin of 32600+ 😎 So it would not help much.
Didn't know there is a `--config_file` option. It would come in handy if in `OpenCppCoveragePlugin` there would be a GUI option and facility that will actually dump the cmd text into a temp file and use it via `--config_file`. Until such option exist, how would you recommend to deal with it via VS GUI and `OpenCppCoveragePlugin`? The flow would be quite cumbersome, seems to me.

**Comment by OpenCppCoverage** [comment]
The only workaround I have in mind is to unload some projects and click on `Reset To default`, but it is probably not an option for you.
You can also try to hack [OpenCppCoverageCmdLine.Build](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/blob/master/VSPackage/OpenCppCoverageCmdLine.cs#L46) and instead of returning the full command line, returns something like [--config_file](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Command-line-reference#--config_file-arg) `temporary_file` where `temporary file` contains the `--sources` and `--modules` filters.

I hope it helps,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Some news: I pushed two days ago the last commit of the development to fix this issue. I need some time to check everything works smoothly, then I will release a new version of the plugin with this fix.

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage Plugin 0.9.7.1](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin) should fix the issue.
