### ISSUE TITLE
Cobertura report's timestamp field should contain meaningful value

### ISSUE THREAD

**Issue by horenmar** [OpenCppCoverage/OpenCppCoverage#109]
**Is your feature request related to a problem? Please describe.**
Reports in the Cobertura format have 0 in the `timestamp` field . This can cause problem with external tools that use the field to do some processing on the data. As an example, codecov.io throws away coverage reports that are overly old, which with the timestamp "0", is all of them.

See this Discourse thread where this interaction caused problems with coverage collection for multiple projects: https://community.codecov.io/t/codecov-cannot-analyze-cobertura-reports-from-appveyor/915/1.

**Describe the solution you'd like**
I would like if the reports in the Cobetura format had their `timestamp` field set to when the report was created, or, preferably, when the measurements were done. The reason I suggest to use the time when the report was created is that I do not know whether OpenCppCoverage's binary format contains the information on when it was collected, and I create the Cobertura report by merging many reports in the binary format.

**Comment by OpenCppCoverage** [comment]
Hello,

Sorry for my late answer and thank you for reporting this issue.
I will set the `timestamp` value to the time when the Cobertura report is created as it is easy to implement. I would like to avoid updating the binary format except if there is a strong reason to do so.

If this issue is blocking you, you can probably do a quick fix (No need to open a PR). See [Building OpenCppCoverage](https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/Building-OpenCppCoverage) and https://github.com/OpenCppCoverage/OpenCppCoverage/blob/master/Exporter/CoberturaExporter.cpp#L119

I hope it helps,

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Fixed in [OpenCppCoverage 0.9.9.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.9.0).
