### ISSUE TITLE
Support to count the number of times a line is executed

### ISSUE THREAD

**Issue by eozer** [OpenCppCoverage/OpenCppCoverage#28]
Hi,

First of all, thank you for this great project I've been a follower since the codeplex. 

Referring to your [response message in codeplex](https://archive.codeplex.com/?p=opencppcoverage) (Message #1453928 ) about the support for counting the number of times a line is executed. Is it possible to add this as a feature as I want to make a research on fault localization using code coverage? I have tried to collect coverage information that is similar to gcov but in Windows using Visual Studio's code coverage. But it turns out VS coverage, does not give number of times a line is executed. 

Do you think this feature would be available anyhow? Can you instruct or point out so that I can work on a fork, which will aim to get this information? Or is this even possible?

Thank you.

**Comment by OpenCppCoverage** [comment]
Hello,

I do not plan to add this feature for now.
I think it is not too long to have a beta version with some restriction (slowness, only cobertura). 

Here how OpenCppCoverage works:
1.  Add a breakpoint instruction (0xCC) to each line and save old instruction(*)
2. When the breakpoint is reached, an event is raised and this event is handled in CodeCoverageRunner::OnBreakPoint
3. Old instruction is restored at the breakpoint location
4. In AdjustEipAfterBreakPointRemoval, EIP ASM register is updated to point to the restored old instruction
5. Resume code execution

Instead of step 5 (and so after AdjustEipAfterBreakPointRemoval) you need to :
1. Increase a counter for this address somewhere.
2. Set a special flag to break after executing the next instruction (INT 1) https://stackoverflow.com
/questions/7941988/why-single-stepping-instruction-on-x86
3. Resume execution
4. An event is raised after executed the restored instruction. You need to restore breakpoint in the same way as (*).
5. Resume execution.

This is the general idea. Please let me know if you need more information.

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Hello,

Fell free to open a new discussion if you need more information.

OpenCppCoverage
