### ISSUE TITLE
IAR Embedded Workbench - Support for coverage

### ISSUE THREAD

**Issue by Eldadc** [OpenCppCoverage/OpenCppCoverage#76]
- Architecture (x86/ x64): ____x64_
- Windows version: 7

Is there support for IAR projects?

Thanks

.

**Comment by OpenCppCoverage** [comment]
Hello,

Do you speak about https://www.iar.com/embedded_trust?
If the executable can be debugged with Visual Studio but does not work with OpenCppCoverage, can you provide a full toy example so that I can investigate the issue?
If you cannot debug with Visual Studio then there is no chance it works with OpenCppCoverage.

OpenCppCoverage.

**Comment by Eldadc** [comment]
Hi,

Yes IAR workbench embedded IDE.
Ok I understand.
Thanks

**Comment by Eldadc** [comment]
closed
